### PR TITLE
Etc update "don't change the 'tip the coder' address"

### PR DESCRIPTION
**Pull request by UrsZeidler**
I find it very disturbing that you changed the address of the 'tip the coder', this is not correct as you are not the coder.

You need to change this to, f.e. you can `tip the etc community` by sending some ethers : 0x95D80084D4Fc2CB2063B765676fb328930935e5B

and leave the original 'tip the coder' intact.

I felt very neutral to the etc community but this is a kind of scam in my opinion and if you don't change this in the next two days I will report the abuse.

### CODE REVIEW

**Comment by splix** [comment]
Hi @UrsZeidler, I'm very sorry for the situation. I fully agree that changing tip address to someone's else is absolutely unacceptable. One of the developers cloned your repo and set _his personal address_ (it's not a community address) w/o discussing with the community. 

@ProphetDaniel you cannot take someone's donation for yourself, especially when you're using ETC org as a justification. By doing that your are making harm to ETC community. Please return original tip address. Also I'll really appreciate if you'll move this project to your personal repo. Thank you.

**Comment by UrsZeidler** [comment]
Thanks for the quick response and for the clarification.

> his personal address (not even community address)

Man, this is very bad. If you like I can send the abuse request right now.

**Comment by splix** [comment]
I guess sending abuse can harm ETC community as well. Give us some time, we'll talk to @ProphetDaniel and we'll figure it out. I'm sure he will fix the issue and return original address.

I've checked, he didn't receive any donation to this address, but I understand this a bad precedent for both of us. I'm so sorry for this situation. Thank you for letting us know about that.

**Comment by UrsZeidler** [comment]
To harm the etc community is not my intention. I have no problem to wait some time.
This is not a project which receives a lot of donations, so there is not really money at steak. 

For the etc project it is bad, having people like this.

So really thanks for your fast response and it is good to hear that this not the community acting so strange.

**Comment by ProphetDaniel** [comment]
Sorry, I was in a hurry when I made it. I had no intention harming you or the ETC community. I wanted actually you to be part of this development, @UrsZeidler . I tried contacting you without success. At least for this my actitude had a positive outcome.

**Review by ProphetDaniel — APPROVED** [review]

**Comment by ProphetDaniel** [comment]
@UrsZeidler I made this contribution to UMLGen [UML to C++ Specification](https://wiki.eclipse.org/Eclipse_UML_Generators/Specification/C%2B%2B_Generation/Specification_of_the_C%2B%2B_Generation). What do you think about contributing to UMLGen?

**Comment by UrsZeidler** [comment]
> Sorry, I was in a hurry when I made it.

Hmm, just cloning the rep is much faster than cloning and changing the readme. But hey, as software developers we know: It is normal to make mistakes and correct them.

> I tried contacting you without success.

Create an issue in the repo? A simple thing. But again:  It is normal to make mistakes and correct them.

> What do you think about contributing to UMLGen?

I have contributed to the Java to uml reverse plugin of the topcased project, and they wanted to contribute to the papyrus java importer, so I have made it through the eclipse ip process, as far as I remember, but I'm not sure if they finally put it in.

To have an eclipse based ide for solidity is an interesting project, on which I work partly with the uml2solidity project and my contributions to the https://github.com/webdaford/smart-contract-tools project.

So in my opinion the UMLGen contribution would make sense when there is at least a good working editor for solidity, which smart-contract-tools provides, at least in my private branch, where most of the code completion works. But Dan (the author of the smart-contract-tools) seems really busy and I don't want to take the credits for his work by providing the updatesite for a simple install. (I only provide a private build at http://opensource.urszeidler.de/SolidityEditor-1.0.0-SNAPSHOT.zip for those who want it very badly.)

So, to be honest, I do not see the need of being part of the UMLGen by now. The project is available in the eclipse marketplace, this seems sufficient to me.

We also started on the wrong foot. (Honest again.)

**Pull request closed without merging**
